sonar.projectKey=SkyAgent6CQ_8.2CDevSecOps
sonar.organization=skyagent6cq
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=node_modules/**,test/**,sonar-scanner-*/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8